In [13]:
import numpy as np

np.random.seed(0)

X = [[1,2,3,2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[ 1.07581312 10.39835225  2.44624108  3.1821498   1.88510534]
 [-0.83497962  7.08464114  0.02933567  4.47015253  3.63605378]
 [-5.07632447  5.56884223  0.79877967 -3.48895731  0.45530423]]
[[14.82959991 -8.39760189]
 [14.10031472 -1.3404687 ]
 [20.12497867 -7.29061598]]
